### ISSUE TITLE
Crash when locking and then unlocking screen

### ISSUE THREAD

**Issue by ammichael** [grrrian/phonegap-parse-plugin#15]
Hello there

First, this is the best fork of avivais plugin. Thank you!

But I'm having crash everytime I have the app opened and I lock the screen and unlock it again. Just to make a point here, this just happens when the app closes.

Here the log: 

```
E/AndroidRuntime(31668): FATAL EXCEPTION: main
E/AndroidRuntime(31668): Process: br.com.mobint.bonusQuest, PID: 31668
E/AndroidRuntime(31668): java.lang.RuntimeException: Unable to start receiver com.parse.ParseBroadcastReceiver: java.lang.RuntimeException: applicationContext is null. You must call Parse.initialize(Context) before using the Parse library.
E/AndroidRuntime(31668):    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2618)
E/AndroidRuntime(31668):    at android.app.ActivityThread.access$1700(ActivityThread.java:148)
E/AndroidRuntime(31668):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
E/AndroidRuntime(31668):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(31668):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(31668):    at android.app.ActivityThread.main(ActivityThread.java:5312)
E/AndroidRuntime(31668):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31668):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(31668):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
E/AndroidRuntime(31668):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
E/AndroidRuntime(31668): Caused by: java.lang.RuntimeException: applicationContext is null. You must call Parse.initialize(Context) before using the Parse library.
E/AndroidRuntime(31668):    at com.parse.Parse.checkContext(Parse.java:563)
E/AndroidRuntime(31668):    at com.parse.Parse.getApplicationContext(Parse.java:313)
E/AndroidRuntime(31668):    at com.parse.ManifestInfo.getContext(ManifestInfo.java:322)
E/AndroidRuntime(31668):    at com.parse.ManifestInfo.getPackageManager(ManifestInfo.java:334)
E/AndroidRuntime(31668):    at com.parse.ManifestInfo.getPackageInfo(ManifestInfo.java:368)
E/AndroidRuntime(31668):    at com.parse.ManifestInfo.deviceSupportsGcm(ManifestInfo.java:456)
E/AndroidRuntime(31668):    at com.parse.ManifestInfo.getPushType(ManifestInfo.java:210)
E/AndroidRuntime(31668):    at com.parse.PushService.startServiceIfRequired(PushService.java:222)
E/AndroidRuntime(31668):    at com.parse.ParseBroadcastReceiver.onReceive(ParseBroadcastReceiver.java:19)
E/AndroidRuntime(31668):    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2611)
E/AndroidRuntime(31668):    ... 9 more
```

My App.java:

```
import android.app.Application;
import org.apache.cordova.core.ParsePlugin;

public class App extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        ParsePlugin.initializeParseWithApplication(this);
    }

```

I'm not a Android Dev, so I'm not sure what's happening here. 

Any help will be appreciated!
Thanks

**Comment by cleiton-tavares** [comment]
@ammichael So I had this same problem, and as I did not find solution I ended up changing the original plugin by plugin even though he no longer being maintained, if you want to try the plugin is this -https://github.com/benjie/phonegap-parse-plugin

**Comment by ammichael** [comment]
@cleiton-tavares Thanks for the reply.

Benjie's repo was the first one I've tried, and it was crashing on first app startup.

**Comment by grrrian** [comment]
Hmm... I cannot recreate this bug. Can you please list the steps to reproduce?

Also, it seems like you are calling a method that doesn't exist: initializeParseWithApplication(this).

I have:

```
// register device for parse with the appId and clientKey Strings
Parse.initialize(this, appId, clientKey);
ParseInstallation.getCurrentInstallation().saveInBackground();
```

**Comment by ammichael** [comment]
Well, I just removed every config and Android platform I had, added again and it's working without issues. Don't know what happened, but I'm glad it's working fine.

Thanks @grrrian and @cleiton-tavares!
